Update azure-pipelines.yaml to destroy infrastructure
dfds/ecr-security-scan-notifier pull request #13
Opened 2022-06-21 13:50 UTC by jdsmithit

Change yaml file to tear down the infrastructure

2022-06-21 14:19 UTC, avnes requested changes

2022-06-21 14:19 UTC, avnes commented on azure-pipelines.yaml
> +        script: 'terraform destroy -auto-approve'
Shouldn't you also turn off pipeline triggers to avoid that terraform destroy run all all commits to master. 

Ref:
```

# Triggers Pipeline only on Master
trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - LICENSE
    - azure-pipelines.yaml
```

2022-06-27 06:58 UTC, wcarlsen approved these changes
LGTM if the repo is archived afterwards

2022-06-28 08:10 UTC, jdsmithit commented on azure-pipelines.yaml
> +        script: 'terraform destroy -auto-approve'
I want this to be run over pipeline to destroy the infra @avnes

2022-06-28 09:06 UTC, avnes approved these changes

2022-07-05 08:05 UTC, merged